// Svelte/src/lib/components/biab/Booking.svelte
<script lang="ts">
	/**
	 * Booking — server-rendered event-type list + client-side slot
	 * picker and confirm. Uses Svelte 5 runes for reactive state.
	 *
	 * Slot loads + booking confirms go through `+server.ts` endpoints
	 * under `/api/biab/scheduling/*` — secrets stay on the server.
	 */
	type EventType = {
		id: string;
		name: string;
		slug: string;
		durationMinutes: number;
	};
	type Slot = { startAt: string; endAt: string };

	let { eventTypes }: { eventTypes: EventType[] } = $props();

	let selectedSlug = $state<string | null>(null);
	let slots = $state<Slot[] | null>(null);
	let pickedSlot = $state<string | null>(null);
	let invitee = $state({ name: '', email: '', phone: '', notes: '' });
	let confirming = $state(false);
	let confirmation = $state<string | null>(null);
	let error = $state<string | null>(null);

	// Initialise the dropdown from props inside an effect so prop
	// updates flow through. Svelte 5 warns if you read a prop directly
	// in a `$state(...)` initialiser because the value is captured at
	// init and won't update if the parent re-renders.
	$effect(() => {
		if (selectedSlug === null && eventTypes[0]) {
			selectedSlug = eventTypes[0].slug;
		}
	});

	function startOfTomorrow(): Date {
		const d = new Date();
		d.setDate(d.getDate() + 1);
		d.setHours(0, 0, 0, 0);
		return d;
	}
	function plusWeek(d: Date): Date {
		const next = new Date(d);
		next.setDate(next.getDate() + 7);
		return next;
	}
	function formatSlotTime(iso: string): string {
		return new Date(iso).toLocaleString(undefined, {
			weekday: 'short',
			month: 'short',
			day: 'numeric',
			hour: 'numeric',
			minute: '2-digit',
		});
	}

	async function loadSlots(slug: string) {
		slots = null;
		pickedSlot = null;
		const from = startOfTomorrow();
		const to = plusWeek(from);
		const params = new URLSearchParams({
			slug,
			from: from.toISOString(),
			to: to.toISOString(),
		});
		try {
			const res = await fetch(`/api/biab/scheduling/slots?${params}`);
			if (!res.ok) throw new Error(await res.text());
			const data = (await res.json()) as { slots: Slot[] };
			slots = data.slots;
		} catch (err) {
			error = err instanceof Error ? err.message : 'Unknown error';
			slots = [];
		}
	}

	async function handleConfirm() {
		if (!selectedSlug || !pickedSlot || !invitee.email || !invitee.name) return;
		confirming = true;
		error = null;
		try {
			const res = await fetch('/api/biab/scheduling/bookings', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({
					eventTypeSlug: selectedSlug,
					startAt: pickedSlot,
					invitee: {
						email: invitee.email,
						name: invitee.name,
						phone: invitee.phone || null,
						timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
					},
					notes: invitee.notes || null,
				}),
			});
			if (!res.ok) throw new Error(await res.text());
			const result = (await res.json()) as { bookingId: string };
			confirmation = `Booking confirmed (#${result.bookingId.slice(0, 8)}). Check ${invitee.email} for details.`;
		} catch (err) {
			error = err instanceof Error ? err.message : "Couldn't confirm.";
		} finally {
			confirming = false;
		}
	}

	// Kick off the first slot load once the component mounts.
	$effect(() => {
		if (selectedSlug) loadSlots(selectedSlug);
	});
</script>

<section class="biab-section biab-section--narrow" id="booking">
	{#if confirmation}
		<div class="biab-card booking">
			<span class="biab-badge" style="align-self: flex-start;">Booked</span>
			<h2 class="biab-section__title">You're on the calendar.</h2>
			<p style="color: var(--text);">{confirmation}</p>
		</div>
	{:else}
		<div class="biab-section__lead">
			<span class="biab-section__eyebrow">Schedule</span>
			<h2 class="biab-section__title">Book a time</h2>
			<p class="biab-section__sub">
				Pick a slot and we'll send confirmation + a calendar invite.
			</p>
		</div>
		<div class="biab-card booking">
			{#if eventTypes.length === 0}
				<div class="biab-empty">
					No event types configured yet. Add one in BIAB at Dashboard →
					Scheduling → Event Types.
				</div>
			{:else}
				<div>
					<label class="biab-label" for="event-type">What for?</label>
					<select
						class="biab-select"
						id="event-type"
						bind:value={selectedSlug}
					>
						{#each eventTypes as event (event.slug)}
							<option value={event.slug}>
								{event.name} · {event.durationMinutes}min
							</option>
						{/each}
					</select>
				</div>

				<div>
					<div class="biab-label">Next available slots</div>
					{#if slots === null}
						<div class="biab-loading">Computing availability…</div>
					{:else if slots.length === 0}
						<div class="biab-empty">
							No availability in the next week. Try another event type.
						</div>
					{:else}
						<div class="booking__row">
							{#each slots.slice(0, 12) as slot (slot.startAt)}
								<button
									type="button"
									class="slot-button"
									aria-pressed={pickedSlot === slot.startAt}
									onclick={() => (pickedSlot = slot.startAt)}
								>
									{formatSlotTime(slot.startAt)}
								</button>
							{/each}
						</div>
					{/if}
				</div>

				{#if pickedSlot}
					<div class="field-row field-row--cols">
						<div>
							<label class="biab-label" for="booking-name">Your name</label>
							<input
								class="biab-input"
								id="booking-name"
								bind:value={invitee.name}
								placeholder="Jane Doe"
							/>
						</div>
						<div>
							<label class="biab-label" for="booking-email">Email</label>
							<input
								class="biab-input"
								id="booking-email"
								type="email"
								bind:value={invitee.email}
								placeholder="jane@example.com"
							/>
						</div>
					</div>
					<div>
						<label class="biab-label" for="booking-phone"
							>Phone (optional)</label
						>
						<input
							class="biab-input"
							id="booking-phone"
							type="tel"
							bind:value={invitee.phone}
							placeholder="(555) 555-0100"
						/>
					</div>
					<div>
						<label class="biab-label" for="booking-notes"
							>Anything we should know?</label
						>
						<textarea
							class="biab-textarea"
							id="booking-notes"
							bind:value={invitee.notes}
							placeholder="Optional"
						></textarea>
					</div>
					<button
						type="button"
						class="biab-btn"
						disabled={confirming || !invitee.email || !invitee.name}
						onclick={handleConfirm}
					>
						{confirming
							? 'Confirming…'
							: `Book ${formatSlotTime(pickedSlot)}`}
					</button>
				{/if}

				{#if error}
					<div
						style="color: var(--danger); background: var(--danger-bg); padding: 0.75rem 1rem; border-radius: 0.5rem; font-size: 0.9rem;"
					>
						{error}
					</div>
				{/if}
			{/if}
		</div>
	{/if}
</section>

// Nuxt/app/components/biab/Booking.vue
<script setup lang="ts">
import { ref, watch } from "vue";

import type { EventType } from "../../../server/api/biab/home.get";

type Slot = { startAt: string; endAt: string };

const props = defineProps<{ eventTypes: EventType[] }>();

const selectedSlug = ref<string>(props.eventTypes[0]?.slug ?? "");
const slots = ref<Slot[] | null>(null);
const pickedSlot = ref<string | null>(null);
const inviteeName = ref("");
const inviteeEmail = ref("");
const inviteePhone = ref("");
const inviteeNotes = ref("");
const confirming = ref(false);
const confirmation = ref<string | null>(null);
const error = ref<string | null>(null);

function startOfTomorrow(): Date {
	const d = new Date();
	d.setDate(d.getDate() + 1);
	d.setHours(0, 0, 0, 0);
	return d;
}
function plusWeek(d: Date): Date {
	const next = new Date(d);
	next.setDate(next.getDate() + 7);
	return next;
}
function formatSlotTime(iso: string): string {
	return new Date(iso).toLocaleString(undefined, {
		weekday: "short",
		month: "short",
		day: "numeric",
		hour: "numeric",
		minute: "2-digit",
	});
}

// Re-load slots whenever the selected event type changes.
watch(
	selectedSlug,
	async (slug) => {
		if (!slug) return;
		slots.value = null;
		pickedSlot.value = null;
		try {
			const from = startOfTomorrow().toISOString();
			const to = plusWeek(startOfTomorrow()).toISOString();
			const result = await $fetch<{ slots: Slot[] }>(
				"/api/biab/scheduling/slots",
				{ params: { slug, from, to } },
			);
			slots.value = result.slots;
		} catch (err) {
			error.value = err instanceof Error ? err.message : "Unknown error";
			slots.value = [];
		}
	},
	{ immediate: true },
);

async function handleConfirm() {
	if (
		!selectedSlug.value ||
		!pickedSlot.value ||
		!inviteeEmail.value ||
		!inviteeName.value
	)
		return;
	confirming.value = true;
	error.value = null;
	try {
		const result = await $fetch<{ bookingId: string }>(
			"/api/biab/scheduling/bookings",
			{
				method: "POST",
				body: {
					eventTypeSlug: selectedSlug.value,
					startAt: pickedSlot.value,
					invitee: {
						email: inviteeEmail.value,
						name: inviteeName.value,
						phone: inviteePhone.value || null,
						timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
					},
					notes: inviteeNotes.value || null,
				},
			},
		);
		confirmation.value = `Booking confirmed (#${result.bookingId.slice(0, 8)}). Check ${inviteeEmail.value} for details.`;
	} catch (err) {
		error.value = err instanceof Error ? err.message : "Couldn't confirm.";
	} finally {
		confirming.value = false;
	}
}
</script>

<template>
	<section class="biab-section biab-section--narrow" id="booking">
		<template v-if="confirmation">
			<div class="biab-card booking">
				<span class="biab-badge" style="align-self: flex-start;">Booked</span>
				<h2 class="biab-section__title">You're on the calendar.</h2>
				<p style="color: var(--text);">{{ confirmation }}</p>
			</div>
		</template>

		<template v-else>
			<div class="biab-section__lead">
				<span class="biab-section__eyebrow">Schedule</span>
				<h2 class="biab-section__title">Book a time</h2>
				<p class="biab-section__sub">
					Pick a slot and we'll send confirmation + a calendar invite.
				</p>
			</div>

			<div class="biab-card booking">
				<div v-if="eventTypes.length === 0" class="biab-empty">
					No event types configured yet. Add one in BIAB at Dashboard →
					Scheduling → Event Types.
				</div>
				<template v-else>
					<div>
						<label class="biab-label" for="event-type">What for?</label>
						<select
							v-model="selectedSlug"
							class="biab-select"
							id="event-type"
						>
							<option
								v-for="ev in eventTypes"
								:key="ev.slug"
								:value="ev.slug"
							>
								{{ `${ev.name} · ${ev.durationMinutes}min` }}
							</option>
						</select>
					</div>

					<div>
						<div class="biab-label">Next available slots</div>
						<div v-if="slots === null" class="biab-loading">
							Computing availability…
						</div>
						<div v-else-if="slots.length === 0" class="biab-empty">
							No availability in the next week. Try another event type.
						</div>
						<div v-else class="booking__row">
							<button
								v-for="slot in slots.slice(0, 12)"
								:key="slot.startAt"
								:aria-pressed="pickedSlot === slot.startAt"
								class="slot-button"
								type="button"
								@click="pickedSlot = slot.startAt"
							>
								{{ formatSlotTime(slot.startAt) }}
							</button>
						</div>
					</div>

					<template v-if="pickedSlot">
						<div class="field-row field-row--cols">
							<div>
								<label class="biab-label" for="booking-name">Your name</label>
								<input
									v-model="inviteeName"
									class="biab-input"
									id="booking-name"
									placeholder="Jane Doe"
								/>
							</div>
							<div>
								<label class="biab-label" for="booking-email">Email</label>
								<input
									v-model="inviteeEmail"
									class="biab-input"
									id="booking-email"
									placeholder="jane@example.com"
									type="email"
								/>
							</div>
						</div>
						<div>
							<label class="biab-label" for="booking-phone">
								Phone (optional)
							</label>
							<input
								v-model="inviteePhone"
								class="biab-input"
								id="booking-phone"
								placeholder="(555) 555-0100"
								type="tel"
							/>
						</div>
						<div>
							<label class="biab-label" for="booking-notes">
								Anything we should know?
							</label>
							<textarea
								v-model="inviteeNotes"
								class="biab-textarea"
								id="booking-notes"
								placeholder="Optional"
							></textarea>
						</div>
						<button
							:disabled="confirming || !inviteeEmail || !inviteeName"
							class="biab-btn"
							type="button"
							@click="handleConfirm"
						>
							{{
								confirming
									? "Confirming…"
									: `Book ${formatSlotTime(pickedSlot)}`
							}}
						</button>
					</template>

					<div
						v-if="error"
						style="color: var(--danger); background: var(--danger-bg); padding: 0.75rem 1rem; border-radius: 0.5rem; font-size: 0.9rem;"
					>
						{{ error }}
					</div>
				</template>
			</div>
		</template>
	</section>
</template>
