// T3-App/src/app/_components/biab/ContactForm.tsx
"use client";

import { useState } from "react";

import type { FormSchema } from "@/server/api/routers/biab";
import { api } from "@/trpc/react";

export function ContactForm({
	schema,
	slug,
}: {
	schema: FormSchema;
	slug: string;
}) {
	const [data, setData] = useState<Record<string, string>>({});
	const [confirmation, setConfirmation] = useState<string | null>(null);

	const submit = api.biab.submitForm.useMutation({
		onSuccess: () => {
			setConfirmation("Thanks — we'll be in touch within one business day.");
			setData({});
		},
	});

	function handleSubmit(event: React.FormEvent) {
		event.preventDefault();
		submit.mutate({
			slug,
			data,
			submitterEmail: data.email,
			submitterName: data.name,
		});
	}

	if (confirmation) {
		return (
			<section className="biab-section biab-section--narrow" id="contact">
				<div className="biab-card contact">
					<span className="biab-badge" style={{ alignSelf: "flex-start" }}>
						Received
					</span>
					<h2 className="biab-section__title">Got it.</h2>
					<p>{confirmation}</p>
				</div>
			</section>
		);
	}

	return (
		<section className="biab-section biab-section--narrow" id="contact">
			<div className="biab-section__lead">
				<span className="biab-section__eyebrow">Contact</span>
				<h2 className="biab-section__title">
					{schema.title ?? "Get in touch"}
				</h2>
				{schema.description ? (
					<p className="biab-section__sub">{schema.description}</p>
				) : null}
			</div>
			<form className="biab-card contact" onSubmit={handleSubmit}>
				{schema.fields.map((field) => (
					<div key={field.id}>
						<label className="biab-label" htmlFor={`field-${field.id}`}>
							{field.label}
							{field.required ? " *" : ""}
						</label>
						{field.type === "textarea" ? (
							<textarea
								className="biab-textarea"
								id={`field-${field.id}`}
								onChange={(e) =>
									setData({ ...data, [field.id]: e.target.value })
								}
								placeholder={field.placeholder ?? ""}
								required={field.required}
								value={data[field.id] ?? ""}
							/>
						) : (
							<input
								className="biab-input"
								id={`field-${field.id}`}
								onChange={(e) =>
									setData({ ...data, [field.id]: e.target.value })
								}
								placeholder={field.placeholder ?? ""}
								required={field.required}
								type={field.type === "email" ? "email" : "text"}
								value={data[field.id] ?? ""}
							/>
						)}
						{field.helpText ? (
							<small style={{ color: "var(--text-muted)" }}>
								{field.helpText}
							</small>
						) : null}
					</div>
				))}
				<button
					className="biab-btn"
					disabled={submit.isPending}
					style={{ alignSelf: "flex-start" }}
					type="submit"
				>
					{submit.isPending ? "Sending…" : "Send message"}
				</button>
				{submit.error ? (
					<div
						style={{
							color: "var(--danger)",
							background: "var(--danger-bg)",
							padding: "0.75rem 1rem",
							borderRadius: "0.5rem",
							fontSize: "0.9rem",
						}}
					>
						{submit.error.message}
					</div>
				) : null}
			</form>
		</section>
	);
}

// Nuxt/app/components/biab/ContactForm.vue
<script setup lang="ts">
import { reactive, ref } from "vue";

import type { FormSchema } from "../../../server/api/biab/home.get";

const props = defineProps<{ schema: FormSchema; slug: string }>();

const values = reactive<Record<string, string>>({});
const submitting = ref(false);
const confirmation = ref<string | null>(null);
const error = ref<string | null>(null);

async function handleSubmit() {
	submitting.value = true;
	error.value = null;
	try {
		await $fetch(`/api/biab/forms/${encodeURIComponent(props.slug)}`, {
			method: "POST",
			body: {
				data: { ...values },
				submitterEmail: values.email,
				submitterName: values.name,
			},
		});
		confirmation.value = "Thanks — we'll be in touch within one business day.";
		for (const k of Object.keys(values)) delete values[k];
	} catch (err) {
		error.value = err instanceof Error ? err.message : "Couldn't submit.";
	} finally {
		submitting.value = false;
	}
}
</script>

<template>
	<section class="biab-section biab-section--narrow" id="contact">
		<template v-if="confirmation">
			<div class="biab-card contact">
				<span class="biab-badge" style="align-self: flex-start;">Received</span>
				<h2 class="biab-section__title">Got it.</h2>
				<p>{{ confirmation }}</p>
			</div>
		</template>

		<template v-else>
			<div class="biab-section__lead">
				<span class="biab-section__eyebrow">Contact</span>
				<h2 class="biab-section__title">
					{{ schema.title ?? "Get in touch" }}
				</h2>
				<p v-if="schema.description" class="biab-section__sub">
					{{ schema.description }}
				</p>
			</div>

			<form class="biab-card contact" @submit.prevent="handleSubmit">
				<div v-for="field in schema.fields" :key="field.id">
					<label class="biab-label" :for="`field-${field.id}`">
						{{ field.label }}{{ field.required ? " *" : "" }}
					</label>
					<textarea
						v-if="field.type === 'textarea'"
						v-model="values[field.id]"
						class="biab-textarea"
						:id="`field-${field.id}`"
						:placeholder="field.placeholder ?? ''"
						:required="field.required"
					></textarea>
					<input
						v-else
						v-model="values[field.id]"
						class="biab-input"
						:id="`field-${field.id}`"
						:placeholder="field.placeholder ?? ''"
						:required="field.required"
						:type="field.type === 'email' ? 'email' : 'text'"
					/>
					<small v-if="field.helpText" style="color: var(--text-muted);">
						{{ field.helpText }}
					</small>
				</div>
				<button
					:disabled="submitting"
					class="biab-btn"
					style="align-self: flex-start;"
					type="submit"
				>
					{{ submitting ? "Sending…" : "Send message" }}
				</button>
				<div
					v-if="error"
					style="color: var(--danger); background: var(--danger-bg); padding: 0.75rem 1rem; border-radius: 0.5rem; font-size: 0.9rem;"
				>
					{{ error }}
				</div>
			</form>
		</template>
	</section>
</template>
