// T3-App/src/app/_components/biab/Hero.tsx
import type { HeroData } from "@/server/api/routers/biab";

export function Hero({ hero }: { hero: HeroData }) {
	return (
		<section className="hero" id="hero">
			<span className="biab-badge">Open · Mon–Sat</span>
			<h1 className="hero__title">{hero.title}</h1>
			<p className="hero__sub">{hero.tagline}</p>
			<a className="biab-btn" href={hero.ctaHref}>
				{hero.ctaLabel}
			</a>
		</section>
	);
}

// Nuxt/app/components/biab/Hero.vue
<script setup lang="ts">
import type { HeroData } from "../../../server/api/biab/home.get";

defineProps<{ hero: HeroData }>();
</script>

<template>
	<section class="hero" id="hero">
		<span class="biab-badge">Open · Mon–Sat</span>
		<h1 class="hero__title">{{ hero.title }}</h1>
		<p class="hero__sub">{{ hero.tagline }}</p>
		<a class="biab-btn" :href="hero.ctaHref">{{ hero.ctaLabel }}</a>
	</section>
</template>
