// Tanstack-Start/solid/src/components/biab/ContactForm.tsx
import { createSignal, For, Show } from "solid-js";

import {
	type FormSchema,
	submitContactForm,
} from "../../lib/biab-server-fns";

export function ContactForm(props: { schema: FormSchema; slug: string }) {
	const [values, setValues] = createSignal<Record<string, string>>({});
	const [submitting, setSubmitting] = createSignal(false);
	const [confirmation, setConfirmation] = createSignal<string | null>(null);
	const [error, setError] = createSignal<string | null>(null);

	async function handleSubmit(event: SubmitEvent) {
		event.preventDefault();
		setSubmitting(true);
		setError(null);
		try {
			await submitContactForm({
				data: { slug: props.slug, values: values() },
			});
			setConfirmation(
				"Thanks — we'll be in touch within one business day.",
			);
			setValues({});
		} catch (err) {
			setError(err instanceof Error ? err.message : "Couldn't submit.");
		} finally {
			setSubmitting(false);
		}
	}

	return (
		<section class="biab-section biab-section--narrow" id="contact">
			<Show
				when={!confirmation()}
				fallback={
					<div class="biab-card contact">
						<span class="biab-badge" style="align-self: flex-start;">
							Received
						</span>
						<h2 class="biab-section__title">Got it.</h2>
						<p>{confirmation()}</p>
					</div>
				}
			>
				<div class="biab-section__lead">
					<span class="biab-section__eyebrow">Contact</span>
					<h2 class="biab-section__title">
						{props.schema.title ?? "Get in touch"}
					</h2>
					<Show when={props.schema.description}>
						<p class="biab-section__sub">{props.schema.description}</p>
					</Show>
				</div>
				<form class="biab-card contact" onSubmit={handleSubmit}>
					<For each={props.schema.fields}>
						{(field) => (
							<div>
								<label class="biab-label" for={`field-${field.id}`}>
									{field.label}
									{field.required ? " *" : ""}
								</label>
								<Show
									when={field.type === "textarea"}
									fallback={
										<input
											class="biab-input"
											id={`field-${field.id}`}
											onInput={(e) =>
												setValues({
													...values(),
													[field.id]: e.currentTarget.value,
												})
											}
											placeholder={field.placeholder ?? ""}
											required={field.required}
											type={field.type === "email" ? "email" : "text"}
											value={values()[field.id] ?? ""}
										/>
									}
								>
									<textarea
										class="biab-textarea"
										id={`field-${field.id}`}
										onInput={(e) =>
											setValues({
												...values(),
												[field.id]: e.currentTarget.value,
											})
										}
										placeholder={field.placeholder ?? ""}
										required={field.required}
										value={values()[field.id] ?? ""}
									/>
								</Show>
								<Show when={field.helpText}>
									<small style="color: var(--text-muted);">
										{field.helpText}
									</small>
								</Show>
							</div>
						)}
					</For>
					<button
						class="biab-btn"
						disabled={submitting()}
						style="align-self: flex-start;"
						type="submit"
					>
						{submitting() ? "Sending…" : "Send message"}
					</button>
					<Show when={error()}>
						<div style="color: var(--danger); background: var(--danger-bg); padding: 0.75rem 1rem; border-radius: 0.5rem; font-size: 0.9rem;">
							{error()}
						</div>
					</Show>
				</form>
			</Show>
		</section>
	);
}

// Svelte/src/lib/components/biab/ContactForm.svelte
<script lang="ts">
	type FieldDef = {
		id: string;
		label: string;
		type: string;
		required: boolean;
		placeholder?: string;
		helpText?: string;
	};
	type Schema = {
		id: string;
		slug: string;
		title?: string;
		description?: string | null;
		fields: FieldDef[];
	};

	let { schema, slug }: { schema: Schema; slug: string } = $props();

	let data = $state<Record<string, string>>({});
	let submitting = $state(false);
	let confirmation = $state<string | null>(null);
	let error = $state<string | null>(null);

	async function handleSubmit(event: SubmitEvent) {
		event.preventDefault();
		submitting = true;
		error = null;
		try {
			const res = await fetch(
				`/api/biab/forms/${encodeURIComponent(slug)}`,
				{
					method: 'POST',
					headers: { 'Content-Type': 'application/json' },
					body: JSON.stringify({
						data,
						submitterEmail: data.email,
						submitterName: data.name,
					}),
				},
			);
			if (!res.ok) throw new Error(await res.text());
			confirmation = "Thanks — we'll be in touch within one business day.";
			data = {};
		} catch (err) {
			error = err instanceof Error ? err.message : "Couldn't submit.";
		} finally {
			submitting = false;
		}
	}
</script>

<section class="biab-section biab-section--narrow" id="contact">
	{#if confirmation}
		<div class="biab-card contact">
			<span class="biab-badge" style="align-self: flex-start;">Received</span>
			<h2 class="biab-section__title">Got it.</h2>
			<p>{confirmation}</p>
		</div>
	{:else}
		<div class="biab-section__lead">
			<span class="biab-section__eyebrow">Contact</span>
			<h2 class="biab-section__title">{schema.title ?? 'Get in touch'}</h2>
			{#if schema.description}
				<p class="biab-section__sub">{schema.description}</p>
			{/if}
		</div>
		<form class="biab-card contact" onsubmit={handleSubmit}>
			{#each schema.fields as field (field.id)}
				<div>
					<label class="biab-label" for={`field-${field.id}`}>
						{field.label}{field.required ? ' *' : ''}
					</label>
					{#if field.type === 'textarea'}
						<textarea
							class="biab-textarea"
							id={`field-${field.id}`}
							placeholder={field.placeholder ?? ''}
							required={field.required}
							bind:value={data[field.id]}
						></textarea>
					{:else}
						<input
							class="biab-input"
							id={`field-${field.id}`}
							type={field.type === 'email' ? 'email' : 'text'}
							placeholder={field.placeholder ?? ''}
							required={field.required}
							bind:value={data[field.id]}
						/>
					{/if}
					{#if field.helpText}
						<small style="color: var(--text-muted);">{field.helpText}</small>
					{/if}
				</div>
			{/each}
			<button
				class="biab-btn"
				type="submit"
				disabled={submitting}
				style="align-self: flex-start;"
			>
				{submitting ? 'Sending…' : 'Send message'}
			</button>
			{#if error}
				<div
					style="color: var(--danger); background: var(--danger-bg); padding: 0.75rem 1rem; border-radius: 0.5rem; font-size: 0.9rem;"
				>
					{error}
				</div>
			{/if}
		</form>
	{/if}
</section>
