// T3-App/src/app/_components/biab/Header.tsx
export function BiabHeader() {
	return (
		<header className="app-header">
			<div className="app-header__inner">
				<div className="app-header__brand">Your Business</div>
				<nav>
					<a href="#services">Services</a>
					<a href="#gallery">Gallery</a>
					<a href="#booking">Book</a>
					<a href="#blog">Blog</a>
					<a href="#contact">Contact</a>
				</nav>
			</div>
		</header>
	);
}

// Svelte/src/lib/components/biab/Header.svelte
<header class="app-header">
	<div class="app-header__inner">
		<div class="app-header__brand">Your Business</div>
		<nav>
			<a href="#services">Services</a>
			<a href="#gallery">Gallery</a>
			<a href="#booking">Book</a>
			<a href="#blog">Blog</a>
			<a href="#contact">Contact</a>
		</nav>
	</div>
</header>
