// React-Bun/src/components/Header.tsx
export function Header() {
	return (
		<header className="app-header">
			<div className="app-header__inner">
				<div className="app-header__brand">Your Business</div>
				<nav>
					<a href="#services">Services</a>
					<a href="#gallery">Gallery</a>
					<a href="#booking">Book</a>
					<a href="#blog">Blog</a>
					<a href="#contact">Contact</a>
				</nav>
			</div>
		</header>
	);
}

// Angular/Angular/src/app/sections/header.component.ts
import { ChangeDetectionStrategy, Component } from "@angular/core";

@Component({
	selector: "biab-header",
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		<header class="header">
			<a class="brand" href="#hero">Your Business</a>
			<nav>
				<a href="#about">About</a>
				<a href="#services">Services</a>
				<a href="#blog">Blog</a>
				<a href="#contact">Contact</a>
			</nav>
		</header>
	`,
})
export class HeaderComponent {}
