// Tanstack-Start/solid/src/routes/index.tsx
import { createFileRoute } from "@tanstack/solid-router";

import { About } from "../components/biab/About";
import { Blog } from "../components/biab/Blog";
import { Booking } from "../components/biab/Booking";
import { ContactForm } from "../components/biab/ContactForm";
import { BiabFooter } from "../components/biab/Footer";
import { Gallery } from "../components/biab/Gallery";
import { BiabHeader } from "../components/biab/Header";
import { Hero } from "../components/biab/Hero";
import { Services } from "../components/biab/Services";
import { getHomeData } from "../lib/biab-server-fns";

/**
 * `loader` runs `getHomeData` (a `createServerFn`) — server-side
 * during SSR, server-side again on client navigation. Five SDK
 * calls fan out in parallel; the component receives the fully
 * resolved data via `useLoaderData()`. No spinners, no client
 * key, no transport boilerplate.
 */
export const Route = createFileRoute("/")({
	component: App,
	loader: () => getHomeData(),
});

function App() {
	const data = Route.useLoaderData();

	return (
		<>
			<BiabHeader />
			<main>
				<Hero hero={data().hero} />
				<About body={data().about} />
				<Services services={data().services} />
				<Gallery items={data().gallery} />
				<Booking eventTypes={data().eventTypes} />
				<Blog posts={data().blogPosts} />
				<ContactForm schema={data().formSchema} slug={data().formSlug} />
			</main>
			<BiabFooter />
		</>
	);
}

// Svelte/src/routes/+page.svelte
<script lang="ts">
	import About from '$lib/components/biab/About.svelte';
	import Blog from '$lib/components/biab/Blog.svelte';
	import Booking from '$lib/components/biab/Booking.svelte';
	import ContactForm from '$lib/components/biab/ContactForm.svelte';
	import Footer from '$lib/components/biab/Footer.svelte';
	import Gallery from '$lib/components/biab/Gallery.svelte';
	import Header from '$lib/components/biab/Header.svelte';
	import Hero from '$lib/components/biab/Hero.svelte';
	import Services from '$lib/components/biab/Services.svelte';

	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();
</script>

<Header />
<main>
	<Hero hero={data.hero} />
	<About body={data.about} />
	<Services services={data.services} />
	<Gallery items={data.gallery} />
	<Booking eventTypes={data.eventTypes} />
	<Blog posts={data.blogPosts} />
	<ContactForm schema={data.formSchema} slug={data.formSlug} />
</main>
<Footer />
